version: '2'
services:
  web:
    depends_on: [db]
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'postgresql://root:password@db:5432/testdb'
  db:
    build: db
    image: postgres:10
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
      - POSTGRES_DB_HOST=db
    ports:
      - "5432:5432"
    expose:
      - 5432
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"